### PR TITLE
Add JS minification and Update Css/JS minified files auto renaming

### PR DESCRIPTION
**Pull request by ArslanAmeer**
Added Js minification fully functioning . 
and update css and js minification by auto renaming minified files with *.**min**.css/.js

### CODE REVIEW

**Comment by HannanAkbar** [comment]
Cool! thanks for the PR.

**Comment by ArslanAmeer** [comment]
Its Working Absolutely fine for Me ..!  

jsmin
jsminification

**Comment by HannanAkbar** [comment]
Yes, its working fine 👍 
I referenced your PR to a closed issue.

**Comment by ArslanAmeer** [comment]
@HannanAkbar : Oh .. ok ok..   😁

**Pull request merged**
